// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
	Revoked   bool
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	Location  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
