// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CartItem struct {
	ID          uuid.UUID
	CartID      uuid.UUID
	ProductID   uuid.UUID
	Quantity    int32
	PriceAtTime string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Product struct {
	ID              uuid.UUID
	Title           string
	Supplier        string
	Category        string
	Price           string
	ImageUrl        string
	Description     string
	ProductLocation string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
	Revoked   bool
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	Location  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
